version: "3"
   
services:
  database: # any name
    image: postgres:alpine
    container_name: pg_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_NAME={DB_NAME}
      - DB_USER='{DB_USER}'
      - DB_PASSWORD={DB_PASSWORD}
    network_mode: host

  web: # any name
    build: 
      context: backend
      dockerfile: dockerfile
    container_name: backend
    command: >
     sh -c "python manage.py makemigrations &&
            python manage.py waitfordb &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./backend:/social_media_project/ #get the real-time updates that we makes it to the project into the image
    ports:
      - "5000:5000"
    image: web:django # run the image with django tag
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    network_mode: host

  redis: # Remote Dictionary Server.
    image: redis:alpine
    container_name: redis
    volumes:
      - redis:/data/redis
    ports:
      - 6379:6379
    network_mode: host

  celery:
    container_name: celery
    image: web:django
    restart: always # restart container automatically if it is stopped manually or fails
    command: celery -A social_media_project worker -l INFO # get information in terminal
    volumes:
      - ./backend:/social_media_project/
    depends_on:
      - database
      - redis
    env_file:
      - ./.env
    network_mode: host
    
  celery-beat: 
    container_name: celery_beat
    image: web:django
    restart: always
    command: celery -A social_media_project beat -l INFO
    volumes:
      - ./backend:/social_media_project/
    env_file:
      - ./.env
    depends_on:
      - celery
    network_mode: host

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True 
    # persist our data in flower so that it didn’t go away on every restart of container 
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - celery
    network_mode: host
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./monitor.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - flower
    network_mode: host

networks:
  db: 
    driver: host
  net:
    driver: host
  monitoring:
    driver: host

volumes:
  db: 
  redis:
  web:
  prometheus_data: {}