version: "3"
   
services:
  database: # any name
    image: postgres:alpine
    container_name: pg_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_NAME={DB_NAME}
      - DB_USER='{DB_USER}'
      - DB_PASSWORD={DB_PASSWORD}
    network_mode: host

  web: # any name
    build: 
      context: backend
      dockerfile: dockerfile
    container_name: backend
    command: >
     sh -c "python manage.py makemigrations &&
            python manage.py waitfordb &&
            python manage.py migrate &&
            gunicorn -k uvicorn.workers.UvicornWorker social_media_project.asgi:application --bind 0.0.0.0:5000"
    volumes:
      - ./backend:/webproject/ #get the real-time updates that we makes it to the project into the image
      - static_volume:/webproject/static
      - media_volume:/webproject/media
    ports:
      - "5000:5000"
    image: web:django # run the image with django tag
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    network_mode: host

  redis: # Remote Dictionary Server.
    image: redis:alpine
    container_name: redis
    volumes:
      - redis:/data/redis
    ports:
      - 6379:6379
    network_mode: host

  celery:
    container_name: celery
    image: web:django
    restart: always 
    command: celery -A social_media_project worker -l INFO
    depends_on:
      - database
      - redis
    env_file:
      - ./.env
    network_mode: host
    
  celery-beat: 
    container_name: celery_beat
    image: web:django
    restart: always
    command: celery -A social_media_project beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - celery
    network_mode: host

  flower:
    image: mher/flower
    container_name: flower
    command: celery -A social_media_project flower --url-prefix=flower --auth=motasemalmobayyed@gmail.com --persisten=True 
    # persist our data in flower so that it didn’t go away on every restart of container 
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - celery
    network_mode: host
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./monitor.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx-exporter
    network_mode: host

  nginx:
    build: nginx
    container_name: nginx
    ports:
      - 5050:80
    depends_on:
      - flower
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static
      - media_volume:/media
    network_mode: host

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - 9113:9113
    command: 
      - -nginx.scrape-uri
      - http://localhost/metrics
    depends_on:
      - nginx
    network_mode: host  

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME="postgresql://postgres:password@postgres:5432/shop?sslmode=disable"
    depends_on:
      - database
    network_mode: host 

volumes:
  db: 
  redis:
  web:
  static_volume:
  media_volume: