# python alpine version to make image size as small as possible
FROM python:3.10-alpine

# prevent writing pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# prevent buffering stdout and stderr
ENV PYTHONUNBUFFERED=1

# install postgres client to interact with postgres
RUN apk add --update --no-cache postgresql-client jpeg-dev 
RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev

WORKDIR /social_media_project

RUN python -m venv /social_media_project/env 

COPY . /social_media_project/

# install packages in the file
RUN python -m pip install -U pip && \
    python -m pip install -Ur /social_media_project/requirements.txt

