@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

###

# @name login
POST http://{{host}}/api/v1/auth/login HTTP/1.1    
content-type: {{contentType}}

{
    "email": "motasem@gmail.com",
    "password": "motasem"
}

###
@access = {{login.response.body.$.access}}
@token = Bearer {{access}}
###

GET http://{{host}}/api/v1/posts/ HTTP/1.1    
content-type: {{contentType}}
Authorization: {{token}}

###

GET http://{{host}}/api/v1/posts/ HTTP/1.1    
content-type: {{contentType}}
Authorization: {{token}}