name: django-api-tests
run-name: ${{github.actor}} is learning github actions
on:
    workflow_call: # set workflow call when allow this workflow to run on another workflow
    workflow_dispatch: # to trigger this workflow right on github
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 4
  
  linting:
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Check files using black formatter
        uses: datadog/action-py-black-formatter@v2.1
        id: black_action
        with:
          only_changed_files: "true"
          check_mode: "true"
      - name: Annotate diff changes using reviewdog
        if: steps.black_action.outputs.is_formatted == "true"
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

  # pyre:
  #   needs: setup
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run Pyre Action
        # uses: facebook/pyre-action
  #       with:
  #           requirements-path: './backend/requirements.txt'

  test:
    needs: linting
    steps:
      # checks out your repository onto the runner, allowing you to run scripts or other actions against your code (such as build and test tools). 
      name: checkout code 
        uses: actions/checkout@v3
      - name: Setup python 
        uses: action/setup-python@v4
        with: 
          python-version: 3.10
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f backend/requirements.txt ]; then pip install -Ur ./backend/requirements.txt; fi
      - name: Run tests
        run: |
          cd backend
          python manage.py test